// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc250.RecycleRush.subsystems;

import org.usfirst.frc250.RecycleRush.NavX;
import org.usfirst.frc250.RecycleRush.Utilities;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class PurpleSensor extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	NavX joe;
	private double orientation = 0;
	
	public PurpleSensor () {
		joe = new NavX();
	}
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void setOrientationOffset (double orient) {
    	orientation = Utilities.formatAngle(orient);
    }
    
    public double getHeading() {
		return joe.getYaw() + orientation;
	}
	
	public void test () {
		joe.test();
	}
	
	public void zeroHeading () {
		joe.zeroYaw();
	}
	
	public void smartDashboardPush () {
		SmartDashboard.putNumber("Gyro", getHeading());
	}
}

