// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc250.RecycleRush.commands.Elevator;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc250.RecycleRush.Robot;
import org.usfirst.frc250.RecycleRush.RobotMap;
import org.usfirst.frc250.RecycleRush.subsystems.Elevator.RatchetDirectionEnum;

/**
 *
 */
public class  _ElevatorMotorDown extends Command {

    public _ElevatorMotorDown() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
//    	Robot.elevator.setSpeed(RobotMap.kELEVATOR_MAX_SPEED_DOWN);
    	if (Robot.gripper.isGripperClosed()) {
    		Robot.elevator.slowCrash();
    	} else {
    		Robot.elevator.setSpeed(RobotMap.kELEVATOR_FREEFALL_DOWN_SPEED);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.elevator.setSpeed(0);
    	Robot.elevator.setRatchetDirection(RatchetDirectionEnum.UP);
    }
}
